### ISSUE TITLE
capnp error with Wekan and meteor-spk 0.5.1

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/meteor-spk#36]
@kentonv 

Do you have ideas how this could be fixed? Sandstorm version of Wekan does not start with meteor-spk 0.5.1.

```
Debug log: Test
Staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain shutdown requested.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-04-12T15:46:45.787+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=c4pvDotZFY6YxzCeX
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module '/node_modules/capnp.js'
Require stack:
- /programs/server/boot.js
- /main.js
- /start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.require (/programs/server/boot.js:282:22)
    at module (sandstorm.js:27:21)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /programs/server/app/app.js:19086:1
    at /programs/server/boot.js:398:38
    at Array.forEach (<anonymous>)
    at /programs/server/boot.js:226:21
    at /programs/server/boot.js:461:7
    at Function.run (/programs/server/profile.js:280:14)
    at /programs/server/boot.js:460:13 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/programs/server/boot.js', '/main.js', '/start.js' ]
}
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-04-12T15:46:49.509+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=jinyE8ZeCzJhiqSX8
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module '/node_modules/capnp.js'
Require stack:
- /programs/server/boot.js
- /main.js
- /start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.require (/programs/server/boot.js:282:22)
    at module (sandstorm.js:27:21)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /programs/server/app/app.js:19086:1
    at /programs/server/boot.js:398:38
    at Array.forEach (<anonymous>)
    at /programs/server/boot.js:226:21
    at /programs/server/boot.js:461:7
    at Function.run (/programs/server/profile.js:280:14)
    at /programs/server/boot.js:460:13 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/programs/server/boot.js', '/main.js', '/start.js' ]
}
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-04-12T15:46:52.603+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=R4BZga8fYDmzsQJvt
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module '/node_modules/capnp.js'
Require stack:
- /programs/server/boot.js
- /main.js
- /start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.require (/programs/server/boot.js:282:22)
    at module (sandstorm.js:27:21)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /programs/server/app/app.js:19086:1
    at /programs/server/boot.js:398:38
    at Array.forEach (<anonymous>)
    at /programs/server/boot.js:226:21
    at /programs/server/boot.js:461:7
    at Function.run (/programs/server/profile.js:280:14)
    at /programs/server/boot.js:460:13 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/programs/server/boot.js', '/main.js', '/start.js' ]
}
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
```

**Comment by ocdtrekkie** [comment]
This is the same error the Meteor test app has had in the Sandstorm repo. Did this update fix it for that and break it for Wekan? I haven't checked.

**Comment by xet7** [comment]
I have got this error always with 0.5.1. I did redownload this file:
```
 curl https://dl.sandstorm.io/meteor-spk-0.5.1.tar.xz | tar Jxf -
```
And after rebuild there is still same error.

This does not happen with meteor-spk 0.5.0.

**Comment by xet7** [comment]
@ocdtrekkie 

Where is the Meteor test app?

**Comment by ocdtrekkie** [comment]
I checked and the can't find capnp error no longer happens during the tests after this update. So fixing how it got capnp broke it for Wekan.

Meteor test app is in the main Sandstorm repo somewhere.

**Comment by ocdtrekkie** [comment]
meteor-testapp folder in the Sandstorm repo.

**Comment by xet7** [comment]
@ocdtrekkie 

Anyway, I published Wekan v3.95 still with old meteor-spk 0.5.0. Wekan v3.95 [these changes](https://github.com/wekan/wekan/blob/master/CHANGELOG.md).

**Comment by xet7** [comment]
I think I need to add this capnp folder to Wekan too, and test again.
https://github.com/sandstorm-io/sandstorm/tree/master/meteor-testapp/capnp

**Comment by xet7** [comment]
I'm just thinking, why on meteor-spk 0.5.0 archive there is file `meteor-spk.deps/node_modules/capnp.js` and `meteor-spk.deps/node_modules/capnp/` directory with some files, and they don't exist at meteor-spk 0.5.1 archive.

**Comment by kentonv** [comment]
It looks like [Wekan has a work-around for the previous capnp lookup issues](https://github.com/wekan/wekan/blob/9b905c2833d54cf34d1875148075b2bf756d943a/sandstorm.js#L25-L27):

```javascript
const pathParts = process.cwd().split('/');
const path = pathParts.join('/');
const Capnp = Npm.require(`${path}../../../node_modules/capnp.js`);
```

This work-around is no longer required, and no longer works. Instead, replace this with:

```javascript
const Capnp = Npm.require('capnp');
````

**Comment by xet7** [comment]
[Sandstorm Wekan v3.96 released](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v396-2020-04-15-wekan-release) with Meteor 1.10.1 and Node 12.16.2.
